# -*- coding: utf-8 -*-
""".Functions and loops

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tRfkDs1k3B9jnVS7Z80EQuDBoU-C0TeM
"""

class Human:
    def method1(self):
        print("method 1 of human class")
    def method2(self):
      return "allen is eating food"

obj=Human()
obj.method1()
print("text is from human class,",obj.method2())

class Human:
    def method1(self):
        print("method 1 of human class")
    def method2(self):
        return "allen is eating food"

obj = Human()
obj.method1()
print("text is from human class:", obj.method2())

class Employee:
  def method1(self):
    print("Hii,My name is Himani")
  def method2(self):
    return "My id is id1"
  def method3(self):
    return "my profession is data scientist"

obj=Employee()
obj.method1()
print("information abt employee",obj.method2())
print("information abt employee",obj.method3())

class Employee:
    def __init__(self, name, id):
        self.name = name
        self.id = id

    def display(self):
        print(f"ID: {self.id} \nName: {self.name}")

emp1 = Employee("John", 10)
emp2 = Employee("Himani", 11)

emp1.display()
emp2.display()

class Employee:
  id =10
  name="john"
  def display(self):
     print("ID:%d \n Name=%s" %(self.id,self.name))
emp=Employee()
emp.display()

class Human:
  def method1(self):
    print("method1 of human class")
  def method2(self):
    return "allen is eating food"

class Animal:
  def method3(self):
     print("method3 of animal class")
  def method4(self):
    return "dog is barking"

obj1=Human()
obj1.method1()
print("text from human class",obj1.method2())
obj2=Animal()
obj2.method3()
print("text is from animal class",obj2.method4())

class Student:
  def method1(self):
    print("employee name is alice")
  def method2(self):
    return "age is 23"
  def method3(self):
    return "my profession is engineer"
  def method4(self):
    return " The employee belongs from bangalore"
obj=Student()
obj.method1()
print("information abt employee",obj.method2())
print("information abt employee",obj.method3())
print("information abt employee",obj.method4())

class Student:
  def __init__(self,id,name,age,job,email,phone_no):
    self.id=id
    self.name=name
    self.age=age
    self.job=job
    self.email=email
    self.phone_no=phone_no
  def info(self):
    return f"details are: id {self.id} name {self.name} age {self.age} job {self.job} email {self.email} phone_no {self.phone_no}"
  details=Student(1,"Alice",23,"engineer","alice@gmail.com","9765432765")
  print(details.info())

class Student:
    def __init__(self, id, name, age, job, email, phone_no):
        self.id = id
        self.name = name
        self.age = age
        self.job = job
        self.email = email
        self.phone_no = phone_no
    def info(self):
        return f"Details: Name={self.name}, Age={self.age}, Job={self.job}, Email={self.email}"

details = Student(1, "Himani", 21, "Data Scientist", "himani@email.com", "9876543210")
print(details.info())

class Student:
    def __init__(self, id, name, age, job, email, phone_no):
        self.id = id
        self.name = name
        self.age = age
        self.job = job
        self.email = email
        self.phone_no = phone_no

    def info(self):
        print(f"Details are: Name: {self.name}, ID: {self.id}, Age: {self.age}, Job: {self.job}, Email: {self.email}, Phone: {self.phone_no}")
details = Student(1, "Alice", 23, "Engineer", "alice@gmail.com", "9765432765")
details.info()

class student:
  def __init__(self,name,id,age):
    self.name=name
    self.id=id
    self.age=age
s=student("Allen",18,22)
print(getattr(s,'name'))
setattr(s,'age',23)
print(getattr(s,'age'))
print(hasattr(s,'id'))
delattr(s,'age')
print(hasattr(s,'age'))

matrix = [
    [1, 2],
    [3, 4],
    [5, 6]
]

rows = len(matrix)
cols = len(matrix[0])
transpose = [[0 for _ in range(rows)] for _ in range(cols)]

for r in range(rows):
    for c in range(cols):
        transpose[c][r] = matrix[r][c]
print("Loop Transpose:", transpose)

matrix=[
    [1,2],
    [4,5],
    [7,8]
]
rows=len(mat)

matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7,8,9]
]

transpose = [list(row) for row in zip(*matrix)]
print(transpose)

x=[[1,2,3],[4,5,6],[7,8,9]]
y=[[10,11,12],[13,14,15],[16,17,18]]
result=[[0,0,0],[0,0,0],[0,0,0]]
for i in range(len(x)):
  for j in range(len(x[0])):
    result[i][j]=x[i][j]+y[i][j]
for r in result:
  print(r)

x = [[1,2,3],[4,5,6],[7,8,9]]
y = [[10,11,12],[13,14,15],[16,17,18]]

result = [[a + b for a, b in zip(row_x, row_y)] for row_x, row_y in zip(x, y)]
for r in result:
    print(r)



def func(*args, **kwargs):
    for key, value in kwargs.items():
        print("%s=%s" % (key, value))
    print(args)

func("csk", 'cricket player', first='mahendra', mid='singh', last='dhoni')

class Student:
  def __init__(self,name,id,age):
    self.name=name
    self.id=id
    self.age=age
  def display(self):
    print("Name:%s , Id=%d ,age=%d"%self.name,self.id)
s=student("John",101,22)
print(s.__doc__)
print(s.__dict__)
print(s.__module__)

a=int(input("enter the first number"))
b=int(input("enter the second number"))
try:
  c=a/b
  print(c)
except ZeroDivisionError:
  print("cant divide by zero")

try:
  a=int(input("enter the first number"))
  b=int(input("enter the second number"))
  add=a+b
  divide=a/b
  print("sum=",add)
  print("division=",divide)
except ValueError:
  print("Input must be a number")
except ZeroDivisionError:
  print("Division by zero")

a=int(input("enter the first number"))
b=int(input("enter the second number"))
try:
  result=a/b
except ZeroDivisionError:
  print("Division by zero")
else:
  print("result=",result)

a=int(input("enter the first number"))
b=int(input("enter the second number"))
try:
  if b==0:
    raise exception
  c=a/b
  print(c)
except:
  print("exception raised")

a=int(input("enter the first number"))
b=int(input("enter the second number"))
try:
  result=a/b
except ZeroDivisionError:
  print("division by zero")
else:
  print("result=",result)
finally:
  print("exceuting finally cluase")

try:
  n=int(input("enter the first number"))
  result=10/n
  colors=["red","blue","green"]
  print(colors[3])
  user={"name":"himani"}
  print(user["age"])
  with open("file.txt",r) as file:
    content=file.read()
except ZeroDivisionError:
  print("division by zero")
except ValueError:
  print("value must be number")
except IndexError:
  print("index out of range")
except KeyError:
  print("key not found!")
except FileNotFoundError:
  print("File not found")
else:
  print("result=",result)

print(non















