# -*- coding: utf-8 -*-
"""loops in python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lj8XgURz9ncK1Wgps1o7O5nK4za-pe1R
"""

#For loops

#1)print 1 to 10
for i in range(1,11):
  print(i)

#2)print himani for 5 times
for i in range(5):
  print("himani")

#3)print even numbers from 1 to 20
for i in range(1,20,2):
  print(i)

#4)List looper
sub=['phyics','chemistry','biology','mathematics']
for i in sub:
  print("welcome "+i)

#5)print the string seprately
string=input("enter the string:")
for i in string:
  print(i)

#6)print all the odd numbers
for i in range(1,20,2):
   print(i)

#6)print odd numbers from the range
x=int(input("enter te start range:"))
y=int(input("enter the end range:"))
for i in range(x,y):
  if i%2!=0:
    print(i)

#7)multiplication table
num=int(input("enter the number you want multiplication table of:"))
for i in range(1,11):
  print(f"{num}*{i}={num*i}")

#8)print sqaures of the numbers from 1 to 5
for i in range(1,6):
  print(f"The sqaure of the {i} is,{i**2}")

#9)print sum of the numbers
sum=0
for i in range(1,10):
  sum=sum+i
print(sum)

#10)print pass or fail from the list
l=[56,23,47,89,12,18,99]
for i in l:
  if i>50:
    print("pass")
  else:
    print("fail")

#11)count of the word
word="STATISTICS"
count=0
for i in word:
  count=count+1
print(f"The count of the {count}")

#12)concatenating words
list=['himani','pranathi','inchara']
for i in list:
  print("welcome "+i+" to my Django app")

#13)Reverse the number using the loop
for i in range(10,0,-1):
  print(i)

#14)calculating the average
l=[7,8,3,6]
loop=0
for i in l:
  loop=loop+i
print(loop)
n=len(l)
print(n)
avg=print("The average of the numbers is",loop/n)

#15)finding the numbers
l=[5,3,4,5,6,9,0,8,5]
for i in l:
  if i==0:
    print("FOUND THE 0")
    break
  else:
    print("Not found")

#16)Print sqaure of the numbers from 1 to 15
for i in range(1,16):
  print(f"The sqaure of the {i} is - {i**2}")

#17)Character Count: Iterate through a string and count how many times the letter 'a' appears.
user=input("enter the letter")
word='himani'
count=0
for i in word:
  if i==user:
     count=count+1
print("The number of times the letter repeats is",count)

#18)List Filter: Given a list of numbers, print only the numbers that are divisible by 5.
l=[10,78,98,47,7,5,24,18,99,15,55,70]
for i in l:
  if i%5==0:
    print("The number is divisible by 5 - ", i)

#19)The Accumulator: Calculate the sum of all integers from 1 to $n$, where $n$ is provided by the user.
n=int(input("enter the sum of the numbers you want! "))
sum=0
for i in range(1,n+1):
  sum=sum+i
print(sum)

#20)ndex Matcher: Print every element in a list along with its index position (e.g., "Index 0: Apple").
l=['Apple','Mango','Banana','grapes','pineapple','chikoo','gauva']
index=0

for i in l:
  print("index",index,":",i)
  index=index+1

#21)Nested Grid: Use a nested for loop to print a 5×5 grid of hashtags (#).
for row in range(5):
   for col in range(5):
    print("#",end=" ")
   print()

#21)Vowel Stripper: Given a string, use a loop to print only the consonants.
u=input("enter the string:")
vowels=['a','e','i','o','u','A','E','I','O','U']
for i in u:
    if i not in vowels:
        print("The consonents present in the string are ",i)

#22)The Multiplier: Take a list of numbers and create a new list where each number is multiplied by 10.
l=[2,4,6,8,9,7,5,3,1]
v=[]
for i in l:
  x=i*10
  v.append(x)
print(v)

#23)Reverse Range: Print numbers from 100 down to 0, decreasing by 5 each time.
for i in range(100,-1,-5):
  print(i)

#24)Average Calculator: Given a list of test scores, use a loop to find the average score.
t=[10,78,98,47,7,5,27,18,99,15,55,70]
test=0
for i in t:
  test=test+i
  mark=len(t)
  avg_marks=test/mark
print("The average marks is",avg_marks)

# while loops

#1)The Simple Counter
i=1
while i<11:
  print(i)
  i+=1

#2)The Countdown
i=10
while i>=1:
  print(i)
  i-=1
print("saath karod")

#3)Safety Stop (User Input)
while True:
  u=input("enter the word you want to match:")
  if u=='stop':
    break
  print("you typed it",u)
print("loop exited")

#4) The Sum Accumulator
total=0
while total<50:
   u=int(input("enter the value:"))
   total+=u
   print("current total",total)
print("Target reached or exceeded")

#5)Even Numbers Only
i=2
while i<=20:
  if i%2==0:
    print(i)
  i=i+1

#6)Number Guessing: Pick a secret number; keep asking the user to guess until they get it right.
secret_num=69
while True:
  u=int(input("enter the number:"))
  if u==secret_num:
    print("Got the winner,Thank you")
    break
    print("Try again")

#7)Balance Drain: Start with a "bank balance" of 100. Ask the user for a "withdrawal" amount in a loop until the balance reaches 0 or less.
bank_bal=100

while True:
   u=int(input("enter the amount you want to withdraw:"))
   bank_bal-=u

   if bank_bal<=0:
       print("You are out oof money")
       break

#8)Digit Sum: Given a large integer (like 5432), use a while loop and the modulo operator (%) to find the sum of its digits.
num=5432
t=0
while num>0:
  d=num%10
  t=t+d
  num=num//10
print("The total number of digits is",t)

#9)Password Validator: Prompt for a password until the user enters one that is at least 8 characters long.
password=""
while len(password)<8:
  password=input("enter the password:")
  if len(password)>=8:
    print("The password is of 8 characters")
  else:
    print("The password is not of 8 characters")

#10)Collatz Conjecture If $n$ is even, $n = n/2$; if odd, $n = 3n + 1$. Stop at $n = 1$.
n=int(input("enter a number:"))
while n!=1:
  print(n, end=" -> ")
  if n%2==0:
    n=n/2
  else:
    n=3*n+1
print(n)

#11) Power of Two	Keep dividing a number by 2 as long as it remains even.
n=int(input("enter the value:"))
while n%2==0:
  print(n)
  n=n//2

print("odd number found,Stop! ->",n)

#12)Waiting Game	Simulate a loading bar: add a . every second until 10 dots appear.
import time
dots = 0

print("Loading", end="")
while dots < 10:
    print(".", end="", flush=True)
    time.sleep(1)

print("\nDone!")

#13)Inventory CheckStart with 50; Subtract a random (1–5) until you hit 0 .
checks=50
while checks>0:
   user=int(input("enter the value you want to subtract"))
   checks-=user
   print(f"Subtracted {user}. Remaining: {checks}")
print("Inventory empty! Time to restock.")

#14)Menu Loop Show a menu (1. Start, 2. Options, 3. Quit) until "3" is chosen.
while True:
  print("Menu:")
  print("1.Start")
  print("2.options")
  print("3.Quit")

  choice=input("enter the choice number:")

  if choice=='1':
    print("Let's get ready to start the game")
  elif choice=='2':
    print("Select the options")
  elif choice=='3':
    print("Better to Quit")
    break
  else:
    print("Invalid choice")

#15) The "Mini-Bank" 🏦
balance=100
while True:
  print(f"\nYour current balance is: ${balance}")
  print("1. Check Balance")
  print("2. Withdraw $10")
  print("3. Exit")
  choice=input("Enter your choice: ")
  if choice=='1':
    print(f"Your current balance is: ${balance}")
  elif choice=='2':
    user=int(input("enter the amount you want to withdraw:"))
    balance-=user
    print(f"Your current balance after withdrawing is ${balance} ")
  elif choice=='3':
    print("Thank you workdone,Better to exit now")
    break
  else:
    print("Invalid choice")

